const handycrafts = [
 {
    image:"asset/kulit.28.jpg" ,
    title: "leather knife case belt" ,
    info: "Homemade products made from cowhide and manually sewn by hand"  ,
   ide: "myImgb",
   
   close: "closeb",
   modal: "myModalb",
   caption: "leather knife case belt",
},
 {
    image:"asset/kulit.27.jpg" ,
    title: "leather smoking pipe case" ,
    info: "Homemade products made from cowhide and manually sewn by hand"  ,
  ide: "myImg2b",
    spot: "img02b",
    close: "close2b",
    modal: "myModal2b",
   caption: "leather smoking pipe case",
},
 {
    image:"asset/kulit.26.jpg" ,
    title: "leather handbag" ,
    info: "Homemade products made from cowhide and manually sewn by hand"  ,
  ide: "myImg3b",
    spot: "img03b",
   close: "close3b",
   modal: "myModal3b",
   caption: "leather handbag",
},
 {
    image:"asset/kulit.24.jpg" ,
    title: "leather wallet" ,
    info: "Homemade products made from cowhide and manually sewn by hand"  ,
  ide: "myImg5b",
   spot: "img015b",
   close: "close5b",
   modal: "myModal5b",
   caption: "leather wallet",
},
 {
    image:"asset/kulit.25.jpg" ,
    title: "leather knife case" ,
    info: "Homemade products made from cowhide and manually sewn by hand"  ,
  ide: "myImg6b",  
  spot: "img016b",
   close: "close6b",
   modal: "myModal6b",
   caption: "leather knife case",
},
 {
    image:"asset/kulit.23.jpg" ,
    title: "leather ID card case" ,
    info: "Homemade products made from cowhide and manually sewn by hand"  ,
  ide: "myImg07b",  
   close: "close7b",
   modal: "myModal7b",
   caption: "leather ID card case",
},
 {
    image:"asset/kulit.22.jpg" ,
    title: "leather belt" ,
    info: "Homemade products made from cowhide and manually sewn by hand"  ,
  ide: "myImg08b",  
   close: "close8b",
   modal: "myModal8b",
   caption: "leather belt",
},
 {
    image:"asset/kulit.21.jpg" ,
    title: "leather knife case" ,
    info: "Homemade products made from cowhide and manually sewn by hand"  ,
  ide: "myImg11b",
   spot: "img0111b",
   close: "close11b",
   modal: "myModal11b",
   caption: "leather knife case",
},
 {
    image:"asset/kulit.20.jpg" ,
    title: "leather knife case" ,
    info: "Homemade products made from cowhide and manually sewn by hand"  ,
},
 {
    image:"asset/kulit.19.jpg" ,
    title: "leather key chain" ,
    info: "Homemade products made from cowhide and manually sewn by hand"  ,
}, 
  {
    image:"asset/kulit.5.jpg" ,
    title: "The door handles are covered in leather" ,
    info: "Homemade products made from cowhide and manually sewn by hand"  ,
},
  {
    image:"asset/kulit.18.jpg" ,
    title: "leather girls bag" ,
    info: "Homemade products made from cowhide and manually sewn by hand"  ,
},
  {
    image:"asset/kulit.17.jpg" ,
    title: "card holder" ,
    info: "Homemade products made from cowhide and manually sewn by hand"  ,
},
  {
    image:"asset/kulit.16.jpg" ,
    title: "leather watch" ,
    info: "Homemade products made from cowhide and manually sewn by hand"  ,
},
  {
    image:"asset/kulit.4.jpg" ,
    title: "leather name tag" ,
    info: "Homemade products made from cowhide and manually sewn by hand"  ,
},
 {
    image:"asset/kulit.7.jpg" ,
    title: "sling bag" ,
    info: "Homemade products made from cowhide and manually sewn by hand"  ,
},
  {
    image:"asset/kulit.8.jpg" ,
    title: "card holder" ,
    info: "Homemade products made from cowhide and manually sewn by hand"  ,
},
 {
    image:"asset/kulit.9.jpg" ,
    title: "hand bag" ,
    info: "Homemade products made from cowhide and manually sewn by hand"  ,
},
 {
    image:"asset/kulit.11.jpg" ,
    title: "apron" ,
    info: "Homemade products made from cowhide and manually sewn by hand"  ,
},
  {
    image:"asset/kulit.12.jpg" ,
    title: "folding chair" ,
    info: "Homemade products made from cowhide and manually sewn by hand"  ,
},
  {
    image:"asset/kulit.13.jpg" ,
    title: "picnic box" ,
    info: "Homemade products made from cowhide and manually sewn by hand"  ,
},
  {
    image:"asset/kulit.14.jpg" ,
    title: "match holder" ,
    info: "Homemade products made from cowhide and manually sewn by hand"  ,
},
 

  ]
