const handycrafts = [
 {
    image:"asset/kulit.42.jpg" ,
    title: "Leather Cute Pen Pouch" ,
    info: "The handmade cute red leather pencil case can hold up to your pencils"  ,
   ide: "myImgb",
   
   close: "closeb",
   modal: "myModalb",
   caption: "leather knife case belt",
},
 {
    image:"asset/kulit.41.jpg" ,
    title: "Leather fountain pen stand" ,
    info: "Leather fountain pen stand, Leather Pen Holder, Leather Desk Pen Holder"  ,
   ide: "myImgb",
   
   close: "closeb",
   modal: "myModalb",
   caption: "leather knife case belt",
},
 {
    image:"asset/kulit.40.jpg" ,
    title: "Leather Pen Holder, Pen Stand" ,
    info: "Leather Pen Holder, Pen Stand, Gift For Men, Pencil Stand, Fountain Pen Holder"  ,
   ide: "myImgb",
   
   close: "closeb",
   modal: "myModalb",
   caption: "leather knife case belt",
},
 {
    image:"asset/kulit.39.jpg" ,
    title: "Leather Wallet OUTLAW SPECIAL EDITION" ,
    info: "Leather Wallet OUTLAW SPECIAL EDITION, Dual Function, Custom Made, Full Leather, Wallet With Style."  ,
   ide: "myImgb",
   
   close: "closeb",
   modal: "myModalb",
   caption: "leather knife case belt",
},
 {
    image:"asset/kulit.38.jpg" ,
    title: "Keys holder wallet" ,
    info: "Yellow card holder / Minimalist wallet"  ,
   ide: "myImgb",
   
   close: "closeb",
   modal: "myModalb",
   caption: "leather knife case belt",
},
 {
    image:"asset/kulit.37.jpg" ,
    title: "Grassfed Leather Keychain Wallet" ,
    info: "There's no better way to keep your cards and keys together"  ,
   ide: "myImgb",
   
   close: "closeb",
   modal: "myModalb",
   caption: "leather knife case belt",
},
 {
    image:"asset/kulit.36.jpg" ,
    title: "Lip Balm Holder leather" ,
    info: "Another leather scrap buster and this one does not require sewing"  ,
   ide: "myImgb",
   
   close: "closeb",
   modal: "myModalb",
   caption: "leather knife case belt",
},
 {
    image:"asset/kulit.35.jpg" ,
    title: "leather bottle hanger" ,
    info: "leather bottle hanger, minimalist and cool"  ,
   ide: "myImgb",
   
   close: "closeb",
   modal: "myModalb",
   caption: "leather knife case belt",
},
 {
    image:"asset/kulit.34.jpg" ,
    title: "leather drink bottle holder" ,
    info: "leather drink bottle holder, to hang on the belt"  ,
   ide: "myImgb",
   
   close: "closeb",
   modal: "myModalb",
   caption: "leather knife case belt",
},
 {
    image:"asset/kulit.33.jpg" ,
    title: "leather eyeglass case" ,
    info: "leather eyeglass case, with leather necklace"  ,
   ide: "myImgb",
   
   close: "closeb",
   modal: "myModalb",
   caption: "leather knife case belt",
},
 {
    image:"asset/kulit.32.jpg" ,
    title: "Leather AirPods Pro Case" ,
    info: "Leather AirPods Pro Case / Engraved Leather Case for AirPods Pro"  ,
   ide: "myImgb",
   
   close: "closeb",
   modal: "myModalb",
   caption: "leather knife case belt",
},
 {
    image:"asset/kulit.31.jpg" ,
    title: "leather card case" ,
    info: "Homemade products made from cowhide and manually sewn by hand"  ,
   ide: "myImgb",
   
   close: "closeb",
   modal: "myModalb",
   caption: "leather knife case belt",
},
 {
    image:"asset/kulit.30.jpg" ,
    title: "leather bicycle saddle" ,
    info: "Homemade products made from cowhide and manually sewn by hand"  ,
   ide: "myImgb",
   
   close: "closeb",
   modal: "myModalb",
   caption: "leather knife case belt",
},
 {
    image:"asset/kulit.29.jpg" ,
    title: "leather key wrap" ,
    info: "Homemade products made from cowhide and manually sewn by hand"  ,
   ide: "myImgb",
   
   close: "closeb",
   modal: "myModalb",
   caption: "leather knife case belt",
},
 {
    image:"asset/kulit.28.jpg" ,
    title: "leather knife case belt" ,
    info: "Homemade products made from cowhide and manually sewn by hand"  ,
   ide: "myImgb",
   
   close: "closeb",
   modal: "myModalb",
   caption: "leather knife case belt",
},
 {
    image:"asset/kulit.27.jpg" ,
    title: "leather smoking pipe case" ,
    info: "Homemade products made from cowhide and manually sewn by hand"  ,
  ide: "myImg2b",
    spot: "img02b",
    close: "close2b",
    modal: "myModal2b",
   caption: "leather smoking pipe case",
},
 {
    image:"asset/kulit.26.jpg" ,
    title: "leather handbag" ,
    info: "Homemade products made from cowhide and manually sewn by hand"  ,
  ide: "myImg3b",
    spot: "img03b",
   close: "close3b",
   modal: "myModal3b",
   caption: "leather handbag",
},
 {
    image:"asset/kulit.24.jpg" ,
    title: "leather wallet" ,
    info: "Homemade products made from cowhide and manually sewn by hand"  ,
  ide: "myImg5b",
   spot: "img015b",
   close: "close5b",
   modal: "myModal5b",
   caption: "leather wallet",
},
 {
    image:"asset/kulit.25.jpg" ,
    title: "leather knife case" ,
    info: "Homemade products made from cowhide and manually sewn by hand"  ,
  ide: "myImg6b",  
  spot: "img016b",
   close: "close6b",
   modal: "myModal6b",
   caption: "leather knife case",
},
 {
    image:"asset/kulit.23.jpg" ,
    title: "leather ID card case" ,
    info: "Homemade products made from cowhide and manually sewn by hand"  ,
  ide: "myImg7b",  
  spot: "img017b",
   close: "close7b",
   modal: "myModal7b",
   caption: "leather ID card case",
},
 {
    image:"asset/kulit.22.jpg" ,
    title: "leather belt" ,
    info: "Homemade products made from cowhide and manually sewn by hand"  ,
  ide: "myImg8b",  
  spot: "img018b",
   close: "close8b",
   modal: "myModal8b",
   caption: "leather belt",
},

 {
    image:"asset/kulit.20.jpg" ,
    title: "leather knife case" ,
    info: "Homemade products made from cowhide and manually sewn by hand"  ,
  ide: "myImg12b",
   spot: "img0112b",
   close: "close12b",
   modal: "myModal12b",
   caption: "leather knife case",
},
  {
    image:"asset/kulit.21.jpg" ,
    title: "leather knife case" ,
    info: "Homemade products made from cowhide and manually sewn by hand"  ,
  ide: "myImg11b",
   spot: "img0111b",
   close: "close11b",
   modal: "myModal11b",
   caption: "leather knife case",
},

 
 {
    image:"asset/kulit.19.jpg" ,
    title: "leather key chain" ,
    info: "Homemade products made from cowhide and manually sewn by hand"  ,
  ide: "myImg13b",
   spot: "img0113b",
   close: "close13b",
   modal: "myModal13b",
   caption: "leather key chain",
}, 
  {
    image:"asset/kulit.5.jpg" ,
    title: "The door handles are covered in leather" ,
    info: "Homemade products made from cowhide and manually sewn by hand"  ,
   ide: "myImg14b",
   spot: "img0114b",
   close: "close14b",
   modal: "myModal14b",
   caption: "Door Handle covered in leather",
},
  {
    image:"asset/kulit.18.jpg" ,
    title: "leather girls bag" ,
    info: "Homemade products made from cowhide and manually sewn by hand"  ,
   ide: "myImg15b",
   spot: "img0115b",
   close: "close15b",
   modal: "myModal15b",
   caption: "Homemade Product",
},
  {
    image:"asset/kulit.17.jpg" ,
    title: "card holder" ,
    info: "Homemade products made from cowhide and manually sewn by hand"  ,
   ide: "myImg16b",
   spot: "img0116b",
   close: "close16b",
   modal: "myModal16b",
   caption: "Card Holder",
},
  {
    image:"asset/kulit.16.jpg" ,
    title: "leather watch" ,
    info: "Homemade products made from cowhide and manually sewn by hand"  ,
    ide: "myImg25b",
   spot: "img0125b",
   close: "close25b",
   modal: "myModal25b",
   caption: "leather watch",
},
  {
    image:"asset/kulit.4.jpg" ,
    title: "leather name tag" ,
    info: "Homemade products made from cowhide and manually sewn by hand"  ,
   ide: "myImg17b",
   spot: "img0117b",
   close: "close17b",
   modal: "myModal17b",
   caption: "leather name Tag",
},
 {
    image:"asset/kulit.7.jpg" ,
    title: "sling bag" ,
    info: "Homemade products made from cowhide and manually sewn by hand"  ,
  ide: "myImg18b",
   spot: "img0118b",
   close: "close18b",
   modal: "myModal18b",
   caption: "sling bag",
},
  {
    image:"asset/kulit.8.jpg" ,
    title: "card holder" ,
    info: "Homemade products made from cowhide and manually sewn by hand"  ,
   ide: "myImg19b",
   spot: "img0119b",
   close: "close19b",
   modal: "myModal19b",
   caption: "card holder",
},
 {
    image:"asset/kulit.9.jpg" ,
    title: "hand bag" ,
    info: "Homemade products made from cowhide and manually sewn by hand"  ,
  ide: "myImg20b",
   spot: "img0120b",
   close: "close20b",
   modal: "myModal20b",
   caption: "hand bag",
},
 {
    image:"asset/kulit.11.jpg" ,
    title: "apron" ,
    info: "Homemade products made from cowhide and manually sewn by hand"  ,
  ide: "myImg21b",
   spot: "img0121b",
   close: "close21b",
   modal: "myModal21b",
   caption: "apron",
},
  {
    image:"asset/kulit.12.jpg" ,
    title: "folding chair" ,
    info: "Homemade products made from cowhide and manually sewn by hand"  ,
   ide: "myImg22b",
   spot: "img0122b",
   close: "close22b",
   modal: "myModal22b",
   caption: "folding chair",
},
  {
    image:"asset/kulit.13.jpg" ,
    title: "picnic box" ,
    info: "Homemade products made from cowhide and manually sewn by hand"  ,
   ide: "myImg23b",
   spot: "img0123b",
   close: "close23b",
   modal: "myModal23b",
   caption: "picnic box",
},
  {
    image:"asset/kulit.14.jpg" ,
    title: "match holder" ,
    info: "Homemade products made from cowhide and manually sewn by hand"  ,
   ide: "myImg24b",
   spot: "img0124b",
   close: "close24b",
   modal: "myModal24b",
   caption: "match holder",
},
 

  ]
