const products = [
 
  {
 image:"asset/meuble.3.jpg" ,
    title: "Buy Teak Wood Sofa Set Online | TeakLab" ,
    info: "A sofa set is a truly regal piece of furniture for your home. Finely crafted from the best quality teak wood, its fineness is simply out of this world"  ,
   ide: "myImg",
   
   close: "close",
   modal: "myModal",
   caption: "Teakwood Sofa",
  },
  {
    image:"asset/meuble.4.jpg" ,
    title: "fideliohaus — truebluemeandyou: Japanese Table and Chairs in a" ,
    info: "fideliohaus — truebluemeandyou: Japanese Table and Chairs in a"  ,
    ide: "myImg2",
    spot: "img02",
    close: "close2",
    modal: "myModal2",
   caption: "Japanese Table & Chair",
   },
   {
    image:"asset/meuble.5.jpg" ,
    title: "Crafting Dreams from Timber: Unlock 16,000 Plans" ,
    info: "Experience the satisfaction of crafting functional and beautiful pieces using TedsWoodworking's foolproof plans."  ,
    ide: "myImg3",
    spot: "img03",
   close: "close3",
   modal: "myModal3",
   caption: "TedsWoodWorking",
},

  {
    image:"asset/meuble.7.jpg" ,
    title: "Wonder Walls: Unique Home Masterpieces" ,
    info: "unique home decor unique home decor ideas unique home decorating"  ,
   ide: "myImg5",
   spot: "img015",
   close: "close5",
   modal: "myModal5",
   caption: "Japanese Table & Chair",
},
 {
  image:"asset/meuble.8.jpg" ,
    title: "Arditi Collection Sled Coffee Table Wood in Gray | 13.7 H x 39.5 W x 39.5 D" ,
    info: "Arditi Collection is one of the exclusive designers and producers"  ,
  ide: "myImg6",  
  spot: "img016",
   close: "close6",
   modal: "myModal6",
   caption: "Arditi Collection",
},
  {
  image:"asset/meuble.9.jpg" ,
    title: "Moscow Table" ,
    info: "Glam form an essential function combine to create this must"  ,
   ide: "myImg7",  
   close: "close7",
   modal: "myModal7",
   caption: "Functional Style",
},
  {
  image:"asset/meuble.10.jpg" ,
    title: "Cabinet 01" ,
    info: "An iconic design from Vincent’s archives, revisited."  ,
   ide: "myImg8",  
   close: "close8",
   modal: "myModal8",
   caption: "Iconic Collection",
},
  {
  image:"asset/meuble.6.jpg" ,
    title: "Round Dining Table & Chairs for Small Homes" ,
    info: "Not all of us are lucky to have a huge home with enough space for fancy chairs and dining tables. This space saving dining table works for 4 people but"  ,
 ide: "myImg11",
   spot: "img0111",
   close: "close11",
   modal: "myModal11",
   caption: "Japanese Table & Chair",
},
 
 {
    image:"asset/meuble..1.jpg" ,
    title: "chairs" ,
    info: "various kinds of chairs"  , 
  ide: "myImg9",  
   close: "close9",
   modal: "myModal9",
   caption: "various kinds of chairs",
},
 {
    image:"asset/meuble.1.jpg" ,
    title: "Futuristic Meuble" ,
    info: "My Meuble with artistic theme build with heart and full of functionality"  ,
  ide: "myImg10",  
   close: "close10",
   modal: "myModal10",
   caption: "Futuristic Meuble",
},
 {
  image:"asset/meuble.2.jpg" ,
    title: "My Beautiful Meuble" ,
    info: "The scene and the beautiful landscape will force the creativity to build the meuble to the limit"  ,
  ide: "myImg12",  
   close: "close12",
   modal: "myModal12",
   caption: "Beautiful Meuble",
},

  {
  image:"asset/meuble.11.jpg" ,
    title: "Dumont Armoire - 72\" - Solid Cherry - Teak Finish - Mid Century Modern Inspired" ,
    info: "Product Details, Stunning armoire built entirely in solid wood"  ,
ide: "myImg13",  
   close: "close13",
   modal: "myModal13",
   caption: "Beautiful Meuble",
},

  ]
